# Foodmeup/NutritionBundle/Resources/config/doctrine/Ingredient.IngredientContent.orm.yml

Foodmeup\NutritionBundle\Entity\Ingredient\IngredientContent:
    type: 'entity'
    table: 'ingredient_content'
    repositoryClass: 'Foodmeup\NutritionBundle\Repository\Ingredient\IngredientContentRepository'

    indexes:
        ingredient_content_uuid_idx:
            columns: [ uuid ]

    uniqueConstraints:
        unique_ingredient_content_uuid:
          columns: [ uuid ]
        unique_ingredient_content_slug:
          columns: [ slug ]
        unique_ingredient_content_by_ingredient_and_lang_and_name:
          columns: [ id_ingredient, lang, name ]

    fields:
        id:
            type: 'integer'
            id: true
            generator:
                strategy: 'AUTO'

        uuid:
            type: 'string'
            lenght: 50
            nullable: false

        status:
            type: 'string'
            lenght: 3
            nullable: false

        createdAt:
            name: 'created_at'
            type: 'datetime'
            nullable: false

        createdBy:
            name: 'created_by'
            type: 'string'
            lenght: 50
            nullable: false

        updatedAt:
            name: 'updated_at'
            type: 'datetime'
            nullable: true

        updatedBy:
            name: 'updated_by'
            type: 'string'
            lenght: 50
            nullable: true

        name:
            type: 'string'
            lenght: 255
            nullable: false

        slug:
            type: 'string'
            lenght: 255
            nullable: false

        lang:
            type: 'string'
            lenght: 5
            nullable: false

    manyToOne:
        ingredient:
            targetEntity: 'Foodmeup\NutritionBundle\Entity\Ingredient\Ingredient'
            inversedBy: "contents"
            joinColumn:
                name: 'id_ingredient'
                referencedColumnName: 'id'
                nullable: false
