# Foodmeup/NutritionBundle/Resources/config/doctrine/Ingredient.Ingredient.orm.yml

Foodmeup\NutritionBundle\Entity\Ingredient\Ingredient:
    type: 'entity'
    table: 'ingredient'
    repositoryClass: 'Foodmeup\NutritionBundle\Repository\Ingredient\IngredientRepository'

    indexes:
        ingredient_uuid_idx:
            columns: [ uuid ]
        ingredient_origfdcd_idx:
            columns: [ origfdcd ]

    uniqueConstraints:
        unique_ingredient_uuid:
            columns: [ uuid ]
        unique_ingredient_origfdcd:
            columns: [ origfdcd ]

    fields:
        id:
            type: 'integer'
            id: true
            generator:
                strategy: 'AUTO'

        uuid:
            type: 'string'
            lenght: 50
            nullable: false

        status:
            type: 'string'
            lenght: 3
            nullable: false

        createdAt:
            name: 'created_at'
            type: 'datetime'
            nullable: false

        createdBy:
            name: 'created_by'
            type: 'string'
            lenght: 50
            nullable: false

        updatedAt:
            name: 'updated_at'
            type: 'datetime'
            nullable: true

        updatedBy:
            name: 'updated_by'
            type: 'string'
            lenght: 50
            nullable: true

        origfdcd:
            name: 'origfdcd'
            type: 'integer'
            nullable: false

    oneToMany:
        contents:
            targetEntity: 'Foodmeup\NutritionBundle\Entity\Ingredient\IngredientContent'
            mappedBy: 'ingredient'
            cascade: ["remove"]
            JoinColumn:
                nullable: false

    manyToOne:
        family:
            targetEntity: 'Foodmeup\NutritionBundle\Entity\Family\Family'
            inversedBy: "ingredients"
            joinColumn:
                name: 'id_family'
                referencedColumnName: 'id'
                nullable: false
