# app/config/config_prod.yml

imports:
    - { resource: config.yml }

monolog:
    handlers:
        main:
            type:         fingers_crossed
          # 500 errors are logged at the critical level
            action_level: critical
            handler:      grouped
        grouped:
            type:    group
            members: [streamed, buffered]

        streamed:
            type:  stream
            path:  '%kernel.logs_dir%/%kernel.environment%.log'
            level: error
            formatter: request_id_formatter

        buffered:
            type:    buffer
            handler: swift
        swift:
            type:       swift_mailer
            from_email: '%monolog_mail%'
            to_email:   '%monolog_mail%'
            subject:    "[API-FoodMeUp] [%site_host_name%] An Error Occurred!"
            level:      error
