# Foodmeup/NutritionBundle/Resources/config/routing/family/family_content.yml

# FAMILY CONTENTS - API Routing
foodmeup.nutrition.family.list_all_family_contents:
    path:     '/families/{familyUuid}/contents'
    defaults: { _controller: 'foodmeup.nutrition.family_content_query_controller:listAllFamilyContentsAction' }

foodmeup.nutrition.family.get_one_family_content:
    path:     '/families/{familyUuid}/contents/{contentUuid}'
    defaults: { _controller: 'foodmeup.nutrition.family_content_query_controller:getOneFamilyContentAction' }